// Generated by CoffeeScript 1.3.1
(function() {

  describe("Backbone.BindTo", function() {
    return it("is defined", function() {
      return Backbone.BindTo.should.not.be["null"];
    });
  });

}).call(this);
