// Generated by CoffeeScript 1.3.1
(function() {

  describe("Backbone.BindTo", function() {
    var TestCollection, TestModel, TestView, initView;
    TestModel = Backbone.Model;
    TestCollection = Backbone.Collection;
    TestView = Backbone.View.extend({
      initialize: function() {
        var _this = this;
        this.el.innerHTML = this.template;
        return afterEach(function() {
          return _this.remove();
        });
      }
    });
    initView = function(opts, properties) {
      var View;
      if (opts == null) {
        opts = {};
      }
      if (properties == null) {
        properties = {};
      }
      View = TestView.extend(properties);
      return new View(opts);
    };
    it("overwrites the original Backbone.View", function() {
      return Backbone.View.should.be.equal(Backbone.BindTo.View);
    });
    describe("#bindToModel", function() {
      it("can bind to several model events to view actions", function() {
        var model, view;
        model = new TestModel;
        view = initView({
          model: model
        }, {
          name: null,
          email: null,
          bindToModel: {
            'change:name': 'renderName',
            'change:email': 'renderEmail'
          },
          renderName: function() {
            return this.name = this.model.get('name');
          },
          renderEmail: function() {
            return this.email = this.model.get('email');
          }
        });
        model.set('name', 'UserName');
        view.name.should.be.equal('UserName');
        model.set('email', 'UserEmail');
        return view.email.should.be.equal('UserEmail');
      });
      it("doesn't throw an error if bindToModel is not specified", function() {
        return (function() {
          var model, view;
          model = new TestModel;
          view = initView({
            model: model
          });
          return view.remove();
        }).should.not["throw"]();
      });
      it("doesn't throw an error if there isn't a model", function() {
        var view;
        view = initView({
          model: null
        }, {
          bindToModel: {
            'event': 'action'
          }
        });
        return view.remove();
      });
      it("throws an error if view action doesn't exists", function() {
        return (function() {
          var model, view;
          model = new TestModel;
          return view = initView({
            model: model
          }, {
            bindToModel: {
              'event': 'invalid$Action'
            }
          });
        }).should["throw"]('Method invalid$Action does not exist');
      });
      it("throws an error if view action is not an function", function() {
        return (function() {
          var model, view;
          model = new TestModel;
          return view = initView({
            model: model
          }, {
            action: 'String',
            bindToModel: {
              'event': 'action'
            }
          });
        }).should["throw"]('action is not a function');
      });
      return it("unbinds from all model events when the view is removed removed", function() {
        var model, view;
        model = new TestModel;
        view = initView({
          model: model
        }, {
          bindToModel: {
            'event': 'trackEvent'
          },
          eventTracked: false,
          trackEvent: function() {
            return this.eventTracked = true;
          }
        });
        view.remove();
        model.trigger('event');
        return view.eventTracked.should.not.be["true"];
      });
    });
    describe("#bindToCollection", function() {
      it("can bind to several collection events to view actions", function() {
        var collection, view;
        collection = new TestCollection;
        view = initView({
          collection: collection
        }, {
          items: [],
          bindToCollection: {
            'reset': 'resetItems',
            'add': 'addItem'
          },
          resetItems: function() {
            return this.items = this.collection.invoke('get', 'name');
          },
          addItem: function(item) {
            return this.items.push(item.get('name'));
          }
        });
        collection.reset([
          {
            name: 'item-1'
          }, {
            name: 'item-2'
          }
        ]);
        collection.add({
          name: 'item-3'
        });
        return view.items.should.be.eql(['item-1', 'item-2', 'item-3']);
      });
      it("doesn't throw an error if bindToCollection is not specified", function() {
        return (function() {
          var collection, view;
          collection = new TestCollection;
          view = initView({
            collection: collection
          });
          return view.remove();
        }).should.not["throw"]();
      });
      it("doesn't throw an error if there isn't a collection", function() {
        var view;
        view = initView({
          collection: null
        }, {
          bindToCollection: {
            'event': 'action'
          }
        });
        return view.remove();
      });
      it("throws an error if view action doesn't exists", function() {
        return (function() {
          var collection, view;
          collection = new TestCollection;
          return view = initView({
            collection: collection
          }, {
            bindToCollection: {
              'event': 'invalid$Action'
            }
          });
        }).should["throw"]('Method invalid$Action does not exist');
      });
      it("throws an error if view action is not an function", function() {
        return (function() {
          var collection, view;
          collection = new TestCollection;
          return view = initView({
            collection: collection
          }, {
            action: 'String',
            bindToCollection: {
              'event': 'action'
            }
          });
        }).should["throw"]('action is not a function');
      });
      return it("unbinds from all collection events when the view is removed removed", function() {
        var collection, view;
        collection = new TestCollection;
        view = initView({
          collection: collection
        }, {
          bindToCollection: {
            'event': 'trackEvent'
          },
          eventTracked: false,
          trackEvent: function() {
            return this.eventTracked = true;
          }
        });
        view.remove();
        collection.trigger('event');
        return view.eventTracked.should.not.be["true"];
      });
    });
    return describe(".noConflict", function() {
      beforeEach(function() {
        return this.currentView = Backbone.View;
      });
      afterEach(function() {
        return Backbone.View = this.currentView;
      });
      it("restores the Backbone.View to its original value", function() {
        Backbone.BindTo.noConflict();
        return Backbone.View.should.not.be.equal(Backbone.BindTo.View);
      });
      return it("returns the Backbone.BindTo.View", function() {
        return Backbone.BindTo.noConflict().should.be.equal(Backbone.BindTo.View);
      });
    });
  });

}).call(this);
