// Generated by CoffeeScript 1.3.1
(function() {
  var bindTo, previousBackboneView, root, unbindFrom,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  root = this;

  previousBackboneView = root.Backbone.View;

  Backbone.BindTo = {
    VERSION: '1.0.0',
    noConflict: function() {
      root.Backbone.View = previousBackboneView;
      return this.View;
    }
  };

  bindTo = function(object, events) {
    var eventName, methodName, _results;
    _results = [];
    for (eventName in events) {
      methodName = events[eventName];
      if (!this[methodName]) {
        throw new Error("Method " + methodName + " does not exists");
      }
      if (typeof this[methodName] !== 'function') {
        throw new Error("" + methodName + " is not a function");
      }
      _results.push(object.on(eventName, this[methodName], this));
    }
    return _results;
  };

  unbindFrom = function(object, events) {
    var eventName, methodName, _results;
    _results = [];
    for (eventName in events) {
      methodName = events[eventName];
      _results.push(object.off(eventName, this[methodName], this));
    }
    return _results;
  };

  Backbone.BindTo.View = (function(_super) {

    __extends(View, _super);

    View.name = 'View';

    function View() {
      View.__super__.constructor.apply(this, arguments);
      if (this.model) {
        bindTo.call(this, this.model, this.bindToModel);
      }
      if (this.collection) {
        bindTo.call(this, this.collection, this.bindToCollection);
      }
    }

    View.prototype.remove = function() {
      View.__super__.remove.apply(this, arguments);
      if (this.model) {
        unbindFrom.call(this, this.model, this.bindToModel);
      }
      if (this.collection) {
        return unbindFrom.call(this, this.collection, this.bindToCollection);
      }
    };

    return View;

  })(previousBackboneView);

  root.Backbone.View = Backbone.BindTo.View;

}).call(this);
